export const levels = [
    {
        id: "1",
        worldId: 1,
        title: "The Variable Spark",
        story: "You enter the 'Think Like a Dev' valley. A senior dev hands you a broken script. 'In this world, we don't just store data; we name it with purpose,' they say.",
        mission: "Assign the string 'Dev' to a variable named `role` and the number 10 to a variable named `level`.",
        rules: ["Use `const` or `let` for declarations.", "Variable names must match exactly.", "Values must match exactly."],
        interviewInsight: "Variables are more than just labels; they are the memory of your program. In an interview, explain WHY you chose `const` over `let` (immutability vs. re-assignment).",
        initialCode: "// Start coding here\n",
        validationRegex: "hasRole && hasLevel",
        xpReward: 50
    },
    {
        id: "2",
        worldId: 1,
        title: "The Logic Gate",
        story: "The path is blocked by a gate that only opens if the input is correct. 'Code isn't just data; it's decisions,' the dev explains.",
        mission: "Create an `if` statement that checks if a variable `isAuthorized` is true. If it is, set `gateOpen` to true.",
        rules: ["Use a standard `if` block.", "Variables `isAuthorized` and `gateOpen` already exist in the scope."],
        interviewInsight: "Control flow is the skeleton of logic. Interviews often test if you can handle edge cases in your conditions.",
        initialCode: "let isAuthorized = true;\nlet gateOpen = false;\n\n// Add your logic below\n",
        validationRegex: "if\\s*\\(\\s*isAuthorized\\s*\\)\\s*\\{?\\s*gateOpen\\s*=\\s*true",
        xpReward: 50
    },
    {
        id: "3",
        worldId: 1,
        title: "The Infinite Loop hole",
        story: "You see a worker repeating the same task over and over. 'Automation is the heart of efficiency,' they shout over the noise.",
        mission: "Create a `for` loop that runs 10 times (from i = 0 to 9).",
        rules: ["Use a `for` loop.", "Initialize `i` with `let`.", "Loop until `i < 10`."],
        interviewInsight: "Loops are fundamental for processing collections. In interviews, be ready to discuss Big O notation and why you might choose `forEach` vs a `for` loop.",
        initialCode: "// Write a for loop that runs 10 times\n",
        validationRegex: "for\\s*\\(.*let\\s+i\\s*=\\s*0.*i\\s*<\\s*10.*i\\+\\+\\s*\\)",
        xpReward: 60
    },
    {
        id: "4",
        worldId: 1,
        title: "The Functional Key",
        story: "A lock requires a specific sequence of actions. 'Don't repeat yourself,' a voice whispers. 'Wrap it in a function.'",
        mission: "Define a function named `greet` that takes a `name` parameter and returns 'Hello ' + name.",
        rules: ["Function name must be `greet`.", "Must take one parameter.", "Must use the `return` keyword."],
        interviewInsight: "Functions are the building blocks of modular code. Explain 'Pure Functions' in interviews to show you understand side effects.",
        initialCode: "// Define the greet function\n",
        validationRegex: "function\\s+greet\\s*\\(\\s*name\\s*\\)\\s*\\{?\\s*return",
        xpReward: 70
    },
    {
        id: "5",
        worldId: 1,
        title: "The Object Map",
        story: "You find a dusty map. It's not a drawing, but a structured record of coordinates. 'Everything in JS is an object,' the guide notes.",
        mission: "Create an object named `user` with a property `name` set to any string.",
        rules: ["Use `const` to declare the object.", "Property name must be `name`."],
        interviewInsight: "Objects (and Maps) are key for data modeling. Be prepared to explain the difference between an Object and a Map in JS.",
        initialCode: "// Create the user object\n",
        validationRegex: "const\\s+user\\s*=\\s*\\{?\\s*name\\s*:\\s*(['\"]).+\\1",
        xpReward: 80
    },
    {
        id: "6",
        worldId: 1,
        title: "The Hidden Filter",
        story: "A sea of data surrounds you. 'Why look at everything when you only need a part?' the gatekeeper asks.",
        mission: "Use the `filter` method on an array `numbers` to find all values greater than 10. Assign the result to `bigNumbers`.",
        rules: ["Use `.filter()`.", "Variable name must be `bigNumbers`."],
        interviewInsight: "Array methods like `filter`, `map`, and `reduce` are essential for functional programming in JS. Interviews often ask you to implement these from scratch.",
        initialCode: "const numbers = [5, 12, 8, 20, 3];\n// Filter numbers > 10\n",
        validationRegex: "const\\s+bigNumbers\\s*=\\s*numbers\\.filter",
        xpReward: 90
    },
    {
        id: "7",
        worldId: 1,
        title: "The Template Scroll",
        story: "You need to write a message, but the old string concatenation is too messy. 'Use the backticks,' the whisperer guides.",
        mission: "Create a template literal that includes the variable `score`. Assign it to `message`.",
        rules: ["Use backticks ``.", "Include `${score}`."],
        interviewInsight: "Template literals make string manipulation readable. Mention they also support multi-line strings without `\\n`.",
        initialCode: "const score = 100;\n// Create the message\n",
        validationRegex: "const\\s+message\\s*=\\s*`.*\\${score}.*`",
        xpReward: 90
    },
    {
        id: "8",
        worldId: 1,
        title: "The Arrow Flight",
        story: "A bird flies quickly across the valley. 'Short, sharp, and lexical,' it chirps. 'That's the arrow way.'",
        mission: "Convert a function to an arrow function. Define `add` as an arrow function that takes `a` and `b` and returns their sum.",
        rules: ["Use `=>` syntax.", "Variable name must be `add`."],
        interviewInsight: "Arrow functions don't have their own `this`. This is a CRITICAL interview question when discussing scopes and lexical binding.",
        initialCode: "// Define add as an arrow function\n",
        validationRegex: "const\\s+add\\s*=\\s*\\(\\s*a\\s*,\\s*b\\s*\\)\\s*=>",
        xpReward: 100
    },
    {
        id: "9",
        worldId: 1,
        title: "The Destructured Chest",
        story: "You find a chest with many items. 'Take only what you need, directly,' the instruction says.",
        mission: "Destructure the `name` and `age` properties from the `person` object.",
        rules: ["Use destructuring syntax `{ name, age }`.", "Destructure from the `person` variable."],
        interviewInsight: "Destructuring is a clean way to extract data. In interviews, show how it can also be used in function parameters.",
        initialCode: "const person = { name: 'Alice', age: 25, city: 'Tech City' };\n// Destructure name and age\n",
        validationRegex: "const\\s+\\{\\s*name\\s*,\\s*age\\s*\\}\\s*=\\s*person",
        xpReward: 100
    },
    {
        id: "10",
        worldId: 1,
        title: "The Promise of Dawn",
        story: "The night is long, but the dawn is coming. 'Wait for it,' says the timekeeper.",
        mission: "Write the syntax for a new `Promise` that resolves with 'Success'.",
        rules: ["Use `new Promise`.", "Use the `resolve` callback."],
        interviewInsight: "Promises handle asynchronous operations. Explain the difference between `.then()` and `async/await` in your interviews.",
        initialCode: "// Create a new promise\n",
        validationRegex: "new\\s+Promise\\s*\\(\\s*\\(resolve",
        xpReward: 150
    },
    {
        id: "11",
        worldId: 2,
        title: "The HTTP Handshake",
        story: "Welcome to Backend City. A messenger approaches. 'We use different knocks for different requests,' they explain.",
        mission: "Define a constant `method` and set it to the string 'POST'.",
        rules: ["Use `const`.", "Method set to 'POST'."],
        interviewInsight: "GET vs POST is common. GET is for retrieving data (idempotent), POST is for creating data. Always know your HTTP verbs.",
        initialCode: "// Set the HTTP method\n",
        validationRegex: "const\\s+method\\s*=\\s*(['\"])POST\\1",
        xpReward: 100
    },
    {
        id: "12",
        worldId: 2,
        title: "The Query String",
        story: "The city register is huge. 'Tell me exactly who you are looking for,' the clerk demands.",
        mission: "Create a variable `searchQuery` with the value '?id=101'.",
        rules: ["Use `let` or `const`.", "Value must include the '?' prefix."],
        interviewInsight: "Query parameters are used for filtering. Be careful with sensitive data in URLs; they end up in browser history and server logs.",
        initialCode: "// Define the search query\n",
        validationRegex: "searchQuery\\s*=\\s*(['\"])\\?id=101\\1",
        xpReward: 110
    },
    {
        id: "13",
        worldId: 2,
        title: "The JSON Envelope",
        story: "Data here is packed tightly. 'We don't send messy notes,' says the postman.",
        mission: "Create a JS Object called `payload` with a `status` of 'active'.",
        rules: ["Object name: `payload`.", "Property: `status` set to 'active'."],
        interviewInsight: "JSON is the language of the web. Explain why it's preferred over XML in modern APIs (lightweight/JS native).",
        initialCode: "// Define the request payload\n",
        validationRegex: "const\\s+payload\\s*=\\s*\\{?\\s*status\\s*:\\s*(['\"])active\\1",
        xpReward: 120
    },
    {
        id: "14",
        worldId: 2,
        title: "The Fetch Quest",
        story: "You need to pull information from the Cloud Tower.",
        mission: "Write a `fetch` call to 'https://api.dev/data'.",
        rules: ["Use the `fetch` function.", "Pass the correct URL string."],
        interviewInsight: "The Fetch API is built-in. Mention that it returns a Promise and you need to handle the response (e.g., `res.json()`).",
        initialCode: "// Fetch data\n",
        validationRegex: "fetch\\s*\\(\\s*(['\"])https://api\\.dev/data\\1",
        xpReward: 130
    },
    {
        id: "15",
        worldId: 2,
        title: "The Status Decoder",
        story: "You received a reply, but it's just a number.",
        mission: "Define a constant `NOT_FOUND` and set it to 404.",
        rules: ["Variable name: `NOT_FOUND`.", "Value: 404."],
        interviewInsight: "Knowing status codes shows you are a professional. 4xx is client error, 5xx is server error.",
        initialCode: "// Set the status code\n",
        validationRegex: "const\\s+NOT_FOUND\\s*=\\s*404",
        xpReward: 140
    },
    {
        id: "16",
        worldId: 2,
        title: "The Content Secret",
        story: "The server is confused. 'I don't know what you're sending me!'",
        mission: "Define `headers` as an object with property `'Content-Type'` set to `'application/json'`.",
        rules: ["Use an object literal.", "Property name must be 'Content-Type'.", "Value must be 'application/json'."],
        interviewInsight: "Headers provide metadata about the request. 'Content-Type' tells the server how to parse the body.",
        initialCode: "// Define the headers\n",
        validationRegex: "const\\s+headers\\s*=\\s*\\{?\\s*(['\"])Content-Type\\1\\s*:\\s*(['\"])application/json\\2",
        xpReward: 150
    },
    {
        id: "17",
        worldId: 2,
        title: "The Bearer Token",
        story: "The gate to the vault is locked. 'Members only.'",
        mission: "Add an 'Authorization' property to `authHeaders` with value 'Bearer secret123'.",
        rules: ["Property: 'Authorization'.", "Value: 'Bearer secret123'."],
        interviewInsight: "Authorization headers are the standard for API security. Understand Authentication vs Authorization.",
        initialCode: "const authHeaders = {};\n",
        validationRegex: "Authorization\\s*:\\s*(['\"])Bearer\\s+secret123\\1",
        xpReward: 160
    },
    {
        id: "18",
        worldId: 2,
        title: "The Dynamic Path",
        story: "The city has a million doors. 'We need a pattern.'",
        mission: "Create `dynamicUrl` using a template literal for `/api/users/${userId}`.",
        rules: ["Use backticks ``.", "Variable: `userId`."],
        interviewInsight: "Path parameters make APIs flexible. One route can handle millions of entities.",
        initialCode: "const userId = 42;\n",
        validationRegex: "const\\s+dynamicUrl\\s*=\\s*`\\/api\\/users\\/\\${userId}`",
        xpReward: 170
    },
    {
        id: "19",
        worldId: 2,
        title: "The Body Payload",
        story: "The courier arrived with a package. 'The content goes in the body.'",
        mission: "In `fetch`, set `body` to `JSON.stringify({ id: 1 })`.",
        rules: ["Use `JSON.stringify`.", "Body should contain `{ id: 1 }`."],
        interviewInsight: "Request bodies carry data for POST/PUT. Bodies must be strings.",
        initialCode: "fetch('/api', { method: 'POST' });\n",
        validationRegex: "body\\s*:\\s*JSON\\.stringify\\(\\s*\\{\\s*id\\s*:\\s*1\\s*\\}\\s*\\)",
        xpReward: 180
    },
    {
        id: "20",
        worldId: 2,
        title: "The SQL Whisperer",
        story: "In the basement lies the Great Database.",
        mission: "Assign 'SELECT * FROM users' to `query`.",
        rules: ["Value must be 'SELECT * FROM users'."],
        interviewInsight: "SQL basics are a huge plus for JS devs. Understand JOINs and indexes.",
        initialCode: "// SQL query\n",
        validationRegex: "const\\s+query\\s*=\\s*(['\"])SELECT\\s+\\*\\s+FROM\\s+users\\1",
        xpReward: 200
    },
    {
        id: "21",
        worldId: 3,
        title: "The Success Check",
        story: "Welcome to Full-Stack Flow.",
        mission: "If `response.ok` is true, return `response.json()`.",
        rules: ["Use `if (response.ok)`.", "Return `response.json()`."],
        interviewInsight: "Always check response status. Fetch doesn't treat 404/500 as rejections.",
        initialCode: "function check(response) {}\n",
        validationRegex: "if\\s*\\(\\s*response\\.ok\\s*\\)\\s*\\{?\\s*return\\s+response\\.json\\(\\)",
        xpReward: 150
    },
    {
        id: "22",
        worldId: 3,
        title: "The Target Finder",
        story: "Find the specific leaf.",
        mission: "Use `document.querySelector` to find '#app' and assign to `root`.",
        rules: ["Use `document.querySelector`.", "Selector: '#app'."],
        interviewInsight: "DOM manipulation is core. `querySelector` is modern and flexible.",
        initialCode: "// Select it\n",
        validationRegex: "const\\s+root\\s*=\\s*document\\.querySelector\\(\\s*(['\"])#app\\1\\s*\\)",
        xpReward: 160
    },
    {
        id: "23",
        worldId: 3,
        title: "The Silent Listener",
        story: "Give the button a purpose.",
        mission: "Add a 'click' listener to `btn` that calls `handleClick`.",
        rules: ["Use `.addEventListener()`.", "Event: 'click'."],
        interviewInsight: "Events are interactions. Mention 'Event Delegation' for performance points.",
        initialCode: "const btn = document.querySelector('button');\n",
        validationRegex: "btn\\.addEventListener\\(\\s*(['\"])click\\1\\s*,\\s*handleClick\\s*\\)",
        xpReward: 170
    },
    {
        id: "24",
        worldId: 3,
        title: "The Content Creator",
        story: "Put data on the wall.",
        mission: "Set `container.innerHTML` to '<h1>Loaded</h1>'.",
        rules: ["Use `.innerHTML`.", "Value: '<h1>Loaded</h1>'."],
        interviewInsight: "Updating UI is the payoff. Beware of XSS with `innerHTML`.",
        initialCode: "const container = document.querySelector('#container');\n",
        validationRegex: "container\\.innerHTML\\s*=\\s*(['\"])<h1>Loaded<\\/h1>\\1",
        xpReward: 180
    },
    {
        id: "25",
        worldId: 3,
        title: "The Logic Filter",
        story: "Only show what matters.",
        mission: "If `count > 0`, update UI (simulate).",
        rules: ["Use `if (count > 0)`."],
        interviewInsight: "Conditional rendering is vital. In React it's state-driven, in Vanilla it's logic.",
        initialCode: "let count = 5;\n",
        validationRegex: "if\\s*\\(\\s*count\\s*>\\s*0\\s*\\)",
        xpReward: 200
    },
    {
        id: "26",
        worldId: 3,
        title: "The State Machine",
        story: "The UI needs to remember its current state.",
        mission: "Create `state` with `isLoading: false`. Write `toggleLoading` function.",
        rules: ["Use `isLoading` property.", "Function `toggleLoading` flips it."],
        interviewInsight: "State is the source of truth. Understand one-way data flow.",
        initialCode: "let state = { isLoading: true };\n",
        validationRegex: "function\\s+toggleLoading\\s*\\(\\s*\\)\\s*\\{?\\s*state\\.isLoading\\s*=\\s*!state\\.isLoading",
        xpReward: 200
    },
    {
        id: "27",
        worldId: 3,
        title: "The Async Gate",
        story: "The network is slow. 'Wait for it.'",
        mission: "Use `await` on `fetch('/api/data')` and assign to `res`.",
        rules: ["Use `async/await`.", "Variable: `res`."],
        interviewInsight: "Async/Await makes code readable and handles errors better with try/catch.",
        initialCode: "async function load() {\n",
        validationRegex: "const\\s+res\\s*=\\s*await\\s+fetch",
        xpReward: 210
    },
    {
        id: "28",
        worldId: 3,
        title: "The Event Loop",
        story: "Microtasks and macrotasks.",
        mission: "Use `setTimeout` for 'Delayed' after 1000ms.",
        rules: ["Use `setTimeout()`.", "Delay: 1000."],
        interviewInsight: "Classic question. Understand Call Stack vs Task Queue.",
        initialCode: "// Timeout\n",
        validationRegex: "setTimeout\\(\\s*\\(\\s*\\)\\s*=>.*1000\\s*\\)",
        xpReward: 220
    },
    {
        id: "29",
        worldId: 3,
        title: "The Persistent Memory",
        story: "Browser storage basics.",
        mission: "Use `localStorage.setItem` for 'theme' as 'dark'.",
        rules: ["Use `localStorage.setItem()`.", "Key: 'theme', Value: 'dark'."],
        interviewInsight: "LocalStorage is for simple persistent data. It only stores strings.",
        initialCode: "// Store it\n",
        validationRegex: "localStorage\\.setItem\\(\\s*(['\"])theme\\1\\s*,\\s*(['\"])dark\\2\\s*\\)",
        xpReward: 230
    },
    {
        id: "30",
        worldId: 3,
        title: "The Base64 Key",
        story: "Simple encoding.",
        mission: "Use `btoa()` for 'user:pass'.",
        rules: ["Use `btoa()`.", "Input: 'user:pass'."],
        interviewInsight: "Base64 is for encoding, NOT security. Never use it for sensitive data.",
        initialCode: "const encoded = '';\n",
        validationRegex: "const\\s+encoded\\s*=\\s*btoa\\(\\s*(['\"])user:pass\\1\\s*\\)",
        xpReward: 250
    },
    {
        id: "31",
        worldId: 4,
        title: "The Empty Guard",
        story: "Security Dungeon: Trust no one.",
        mission: "If `input` is empty, return `false`.",
        rules: ["Check `!input`.", "Return `false`."],
        interviewInsight: "Input validation is the first defense. Trust nothing from the user.",
        initialCode: "function val(input) {}\n",
        validationRegex: "if\\s*\\(\\s*!input\\s*\\)\\s*\\{?\\s*return\\s+false",
        xpReward: 200
    },
    {
        id: "32",
        worldId: 4,
        title: "The XSS Filter",
        story: "Hijack protection.",
        mission: "Replace '<script>' in `userInput` with empty string.",
        rules: ["Use `.replace()`.", "Target: '<script>'."],
        interviewInsight: "XSS hijacks browsers. Sanitize everything before rendering.",
        initialCode: "const userInput = '<script>';\n",
        validationRegex: "userInput\\.replace\\(\\s*(['\"])<script>\\1\\s*,\\s*(['\"])\\2\\s*\\)",
        xpReward: 220
    },
    {
        id: "33",
        worldId: 4,
        title: "The Strict Header",
        story: "Browser-level protection.",
        mission: "Add `Strict-Transport-Security` header.",
        rules: ["Max age: 31536000."],
        interviewInsight: "HSTS, CSP, and X-Frame-Options are low-effort/high-reward security.",
        initialCode: "const headers = {};\n",
        validationRegex: "(['\"])Strict-Transport-Security\\1\\s*:\\s*(['\"])max-age=31536000\\2",
        xpReward: 240
    },
    {
        id: "34",
        worldId: 4,
        title: "The Hashed Secret",
        story: "Fingerprints, not keys.",
        mission: "Assign 'Security' to `goal` (concept: Salting).",
        rules: ["Salting prevents rainbow table attacks."],
        interviewInsight: "Hashing + Salting is standard. Explain why plain text is a lethal risk.",
        initialCode: "const goal = '';\n",
        validationRegex: "const\\s+goal\\s*=\\s*(['\"])Security\\1",
        xpReward: 250
    },
    {
        id: "35",
        worldId: 4,
        title: "The Flood Wall",
        story: "Rate limiting.",
        mission: "If `requestCount > 100`, return 429.",
        rules: ["Check > 100.", "Status: 429."],
        interviewInsight: "Rate limit to prevent Brute Force. 429 is the standard response.",
        initialCode: "function limit(c) {}\n",
        validationRegex: "if\\s*\\(\\s*requestCount\\s*>\\s*100\\s*\\).*429",
        xpReward: 260
    },
    {
        id: "36",
        worldId: 4,
        title: "The SQL Injection",
        story: "Dirty queries.",
        mission: "Simulate payload: `'; --`.",
        rules: ["Assign to `payload`."],
        interviewInsight: "Parameterized queries are the fix. Never concatenate strings into SQL.",
        initialCode: "const payload = '';\n",
        validationRegex: "const\\s+payload\\s*=\\s*(['\"])';\\s*--\\1",
        xpReward: 280
    },
    {
        id: "37",
        worldId: 4,
        title: "The Broken Lock",
        story: "IDOR awareness.",
        mission: "Check `currentUser.id === requestedUserId`.",
        rules: ["Compare IDs before returning data."],
        interviewInsight: "IDOR is a top risk. Verify every request against the authenticated user.",
        initialCode: "function protect(u, id) {}\n",
        validationRegex: "if\\s*\\(\\s*currentUser\\.id\\s*===?\\s*requestedUserId\\s*\\)",
        xpReward: 300
    },
    {
        id: "38",
        worldId: 4,
        title: "The Leaky Bucket",
        story: "Logging secrets.",
        mission: "Use `delete user.password`.",
        rules: ["Remove it before logging."],
        interviewInsight: "Sensitive data exposure in logs is common. Filter secrets strictly.",
        initialCode: "const user = { p: '123' };\n",
        validationRegex: "delete\\s+user\\.password",
        xpReward: 280
    },
    {
        id: "39",
        worldId: 4,
        title: "The Forged Request",
        story: "CSRF prevention.",
        mission: "Add `csrfToken` property.",
        rules: ["Proof of site origin."],
        interviewInsight: "CSRF tokens ensure the request came from YOUR site, not a third party link.",
        initialCode: "const data = {};\n",
        validationRegex: "csrfToken\\s*:\\s*",
        xpReward: 300
    },
    {
        id: "40",
        worldId: 4,
        title: "Boss Fight: Secure Gate",
        story: "Defense in depth.",
        mission: "Validate, Sanitize, and Check Role.",
        rules: ["Email, Comment replace, and Admin check."],
        interviewInsight: "Security is layered. Secure every part of the application context.",
        initialCode: "function boss(u, e, c) {}\n",
        validationRegex: "email.*replace.*role\\s*===?\\s*(['\"])admin\\1",
        xpReward: 500
    },
    {
        id: "41",
        worldId: 5,
        title: "The Garbage Collector",
        story: "The system is slowing down.",
        mission: "Set `heavyData` to `null`.",
        rules: ["Assign `null`."],
        interviewInsight: "Help the GC by nullifying large object references.",
        initialCode: "let heavyData = [/*...*/];\n",
        validationRegex: "heavyData\\s*=\\s*null",
        xpReward: 300
    },
    {
        id: "42",
        worldId: 5,
        title: "The Set Sentinel",
        story: "Unique keys needed.",
        mission: "Create a `Set` from `duplicates`.",
        rules: ["Use `new Set()`."],
        interviewInsight: "Sets are optimized for unique membership checks.",
        initialCode: "const items = [1,1,2];\n",
        validationRegex: "new\\s+Set",
        xpReward: 310
    },
    {
        id: "43",
        worldId: 5,
        title: "The Map Master",
        story: "Any symbol as a key.",
        mission: "Create a `Map` and set 'status' to 'green'.",
        rules: ["Use `new Map()`."],
        interviewInsight: "Maps allow non-string keys and maintain order.",
        initialCode: "const m = new Map();\n",
        validationRegex: "set\\(\\s*(['\"])status\\1",
        xpReward: 320
    },
    {
        id: "44",
        worldId: 5,
        title: "The Big O Clock",
        story: "Measure efficiency.",
        mission: "Assign 'O(n)' to `complexity`.",
        rules: ["Identify linear time."],
        interviewInsight: "Big O is crucial for scalable algorithm design.",
        initialCode: "const complexity = '';\n",
        validationRegex: "O\\(n\\)",
        xpReward: 330
    },
    {
        id: "45",
        worldId: 5,
        title: "The Debounce Bridge",
        story: "Stop the rapid fire clicks.",
        mission: "If `!isWaiting`, set it to `true`.",
        rules: ["Implement guard."],
        interviewInsight: "Debouncing saves server resources and UI lag.",
        initialCode: "let isWaiting = false;\n",
        validationRegex: "if\\s*\\(\\s*!isWaiting\\s*\\)",
        xpReward: 350
    },
    {
        id: "46",
        worldId: 5,
        title: "The Web Worker",
        story: "Side road for heavy lifting.",
        mission: "New `Worker('heavy.js')`.",
        rules: ["Bg threading."],
        interviewInsight: "Workers keep the main thread free for UI interactions.",
        initialCode: "const w = '';\n",
        validationRegex: "new\\s+Worker",
        xpReward: 360
    },
    {
        id: "47",
        worldId: 5,
        title: "The Lazy Loader",
        story: "Wait for the guest.",
        mission: "Set `img.loading = 'lazy'`.",
        rules: ["Attribute optimization."],
        interviewInsight: "Lazy loading is a quick win for Core Web Vitals.",
        initialCode: "const img = {};\n",
        validationRegex: "lazy",
        xpReward: 370
    },
    {
        id: "48",
        worldId: 5,
        title: "The Memory Leak Hunt",
        story: "Clean up the fountain.",
        mission: "`.removeEventListener('click', handler)`.",
        rules: ["Clean up listeners."],
        interviewInsight: "Orphaned listeners cause subtle, hard-to-track memory issues.",
        initialCode: "btn.removeEventListener();\n",
        validationRegex: "removeEventListener",
        xpReward: 380
    },
    {
        id: "49",
        worldId: 5,
        title: "The Tree Shaker",
        story: "Shake the tree.",
        mission: "Use `export function active`.",
        rules: ["Named export."],
        interviewInsight: "Bundlers use static analysis to drop unused code fragments.",
        initialCode: "function active() {}\n",
        validationRegex: "export\\s+function\\s+active",
        xpReward: 400
    },
    {
        id: "50",
        worldId: 5,
        title: "Boss Fight: System Audit",
        story: "The Grand System is failing. It's bloated, slow, and leaking memory. 'Optimize or perish!'",
        mission: "1. Use a `Set` for uniqueness. 2. Await an async call. 3. Set an image to `lazy`.",
        rules: ["new Set(data)", "await fetch()", "img.loading = 'lazy'"],
        interviewInsight: "Senior developers focus on performance from day one. Show you can audit and fix bottlenecks.",
        initialCode: "async function audit(data, img) {\n  // 1. Unique data\n  // 2. Fetch config\n  // 3. Optimize image\n}\n",
        validationRegex: "Set.*await.*loading.*lazy",
        xpReward: 600
    },
    {
        id: "51",
        worldId: 6,
        title: "The Unit Test",
        story: "Forge of Quality: trust but verify.",
        mission: "If `result !== 10`, throw `Error`.",
        rules: ["Simple assertion."],
        interviewInsight: "Tests are documentation that never goes out of date.",
        initialCode: "const result = 5+5;\n",
        validationRegex: "throw\\s+new\\s+Error",
        xpReward: 300
    },
    {
        id: "52",
        worldId: 6,
        title: "The Mocking Bird",
        story: "Wooden dragons for training.",
        mission: "Assign `Promise.resolve` mock to `api.getData`.",
        rules: ["Mocking."],
        interviewInsight: "Isolate the unit by mocking external dependencies.",
        initialCode: "const api = {};\n",
        validationRegex: "Promise\\.resolve",
        xpReward: 320
    },
    {
        id: "53",
        worldId: 6,
        title: "The Integration Bridge",
        story: "Do they fit?",
        mission: "Call `partA()` and `partB()`.",
        rules: ["Integration check."],
        interviewInsight: "Integration tests catch the gaps between perfect units.",
        initialCode: "function test() {}\n",
        validationRegex: "partA.*partB",
        xpReward: 340
    },
    {
        id: "54",
        worldId: 6,
        title: "The E2E Explorer",
        story: "Walking the whole path.",
        mission: "Call `browser.click('#submit')`.",
        rules: ["Behavioral testing."],
        interviewInsight: "E2E tests catch issues that unit tests physically cannot see.",
        initialCode: "const browser = { click: () => {} };\n",
        validationRegex: "click\\(\\s*(['\"])#submit",
        xpReward: 360
    },
    {
        id: "55",
        worldId: 6,
        title: "The TDD Mantra",
        story: "Red, Green, Refactor.",
        mission: "If `input === 'test'`, return `'pass'`.",
        rules: ["Minimum code for test."],
        interviewInsight: "TDD creates a tight feedback loop and cleaner APIs.",
        initialCode: "function fix(input) {}\n",
        validationRegex: "return\\s*(['\"])pass",
        xpReward: 380
    },
    {
        id: "56",
        worldId: 6,
        title: "The Console Power",
        story: "Advanced lens.",
        mission: "Use `console.table(users)`.",
        rules: ["Effective debugging."],
        interviewInsight: "Productivity is directly tied to how well you can 'see' your state.",
        initialCode: "const users = [];\n",
        validationRegex: "table\\(",
        xpReward: 300
    },
    {
        id: "57",
        worldId: 6,
        title: "The Error Boundary",
        story: "Close the bulkheads.",
        mission: "Use `try/catch` around `runGame()`.",
        rules: ["Resilience engineering."],
        interviewInsight: "A good app doesn't just work; it fails gracefully.",
        initialCode: "// try/catch\n",
        validationRegex: "try.*catch",
        xpReward: 320
    },
    {
        id: "58",
        worldId: 6,
        title: "The Defensive Shield",
        story: "Safety checks.",
        mission: "Check `data && data.user`.",
        rules: ["Null pointer prevention."],
        interviewInsight: "Optional chaining is your best friend in modern JS.",
        initialCode: "function get(data) {}\n",
        validationRegex: "data\\s*&&\\s*data\\.user",
        xpReward: 340
    },
    {
        id: "59",
        worldId: 6,
        title: "The Semantic Version",
        story: "Safe to upgrade?",
        mission: "Assign 'MAJOR' to `type`.",
        rules: ["Breaking change ID."],
        interviewInsight: "SemVer prevents 'Dependency Hell' by versioning contracts.",
        initialCode: "const type = '';\n",
        validationRegex: "MAJOR",
        xpReward: 300
    },
    {
        id: "60",
        worldId: 6,
        title: "The JsDoc Scroll",
        story: "Future traveler legend.",
        mission: "Add `@param {number} val`.",
        rules: ["Documentation."],
        interviewInsight: "Doc comments are the bridge between authors and consumers.",
        initialCode: "function add(val) {}\n",
        validationRegex: "@param",
        xpReward: 300
    },
    {
        id: "61",
        worldId: 6,
        title: "The GitHub Handshake",
        story: "Push to the cloud.",
        mission: "Assign 'git add .' to `cmd`.",
        rules: ["Staging area."],
        interviewInsight: "Git is the pulse of the dev team. Know your stage vs commit.",
        initialCode: "const cmd = '';\n",
        validationRegex: "git\\s+add",
        xpReward: 200
    },
    {
        id: "62",
        worldId: 6,
        title: "The Commit Stamp",
        story: "Future message.",
        mission: "Assign 'git commit -m \"fix\"' to `cmd`.",
        rules: ["Repository record."],
        interviewInsight: "Great commit messages tell the 'WHY', not the 'WHAT'.",
        initialCode: "const cmd = '';\n",
        validationRegex: "commit",
        xpReward: 210
    },
    {
        id: "63",
        worldId: 6,
        title: "The Branching Path",
        story: "Parallel world.",
        mission: "Assign 'git checkout -b dev' to `cmd`.",
        rules: ["Feature isolation."],
        interviewInsight: "Branches keep the main build stable while you experiment.",
        initialCode: "const cmd = '';\n",
        validationRegex: "checkout",
        xpReward: 220
    },
    {
        id: "64",
        worldId: 6,
        title: "The Merge Master",
        story: "Merging roads.",
        mission: "Assign 'git merge dev' to `cmd`.",
        rules: ["Integration sync."],
        interviewInsight: "Conflict resolution is a senior dev superpower.",
        initialCode: "const cmd = '';\n",
        validationRegex: "merge",
        xpReward: 230
    },
    {
        id: "65",
        worldId: 7,
        title: "The SQL Origin",
        story: "In the depths of the data vault, you find the Ancient Query Language.",
        mission: "Assign 'SELECT * FROM users' to `query`.",
        rules: ["Retrieve all data."],
        interviewInsight: "SELECT * is for exploration. In production, always name your columns for performance.",
        initialCode: "const query = '';\n",
        validationRegex: "SELECT\\s+\\*\\s+FROM\\s+users",
        xpReward: 300
    },
    {
        id: "66",
        worldId: 7,
        title: "The Filtered View",
        story: "Tons of data, but you only need the active ones.",
        mission: "Add a WHERE clause for `status = 'active'`.",
        rules: ["Use the WHERE keyword."],
        interviewInsight: "Filtering at the database level is significantly faster than filtering in application code.",
        initialCode: "const query = 'SELECT * FROM users';\n",
        validationRegex: "WHERE\\s+status\\s*=\\s*(['\"])active\\1",
        xpReward: 310
    },
    {
        id: "67",
        worldId: 7,
        title: "The Ordered Scroll",
        story: "The list is messy. Sort it by date.",
        mission: "Use ORDER BY `created_at` DESC.",
        rules: ["Descending order."],
        interviewInsight: "Unordered results are non-deterministic. Always use ORDER BY if position matters.",
        initialCode: "const query = 'SELECT * FROM logs';\n",
        validationRegex: "ORDER\\s+BY\\s+created_at\\s+DESC",
        xpReward: 320
    },
    {
        id: "68",
        worldId: 7,
        title: "The Limiter Gate",
        story: "The bridge can only hold 5 people at once.",
        mission: "Add LIMIT 5 to your query.",
        rules: ["Limit the results."],
        interviewInsight: "Limit prevents catastrophic memory issues when querying massive tables.",
        initialCode: "const query = 'SELECT * FROM data';\n",
        validationRegex: "LIMIT\\s+5",
        xpReward: 330
    },
    {
        id: "69",
        worldId: 7,
        title: "The Distinct Echo",
        story: "Names are repeating. We only need the unique list.",
        mission: "Use the DISTINCT keyword on the `name` column.",
        rules: ["Remove duplicates."],
        interviewInsight: "DISTINCT is powerful but can be heavy. Use it when data duplication is expected in your result set.",
        initialCode: "const query = 'SELECT name FROM users';\n",
        validationRegex: "SELECT\\s+DISTINCT\\s+name",
        xpReward: 340
    },
    {
        id: "70",
        worldId: 7,
        title: "The Logical Bridge",
        story: "Active and verified users only.",
        mission: "Use AND to check both `status = 'active'` and `verified = 1`.",
        rules: ["Multiple conditions."],
        interviewInsight: "AND/OR logic is the foundation of complex business rules in SQL.",
        initialCode: "const query = 'SELECT * FROM users WHERE status = \"active\"';\n",
        validationRegex: "AND\\s+verified\\s*=\\s*1",
        xpReward: 350
    },
    {
        id: "71",
        worldId: 7,
        title: "The Null Void",
        story: "Some boxes are empty. Find them.",
        mission: "Use IS NULL on the `email` column.",
        rules: ["Check for nulls."],
        interviewInsight: "NULL is not the same as zero or an empty string. IS NULL is a unique check.",
        initialCode: "const query = 'SELECT * FROM users WHERE';\n",
        validationRegex: "email\\s+IS\\s+NULL",
        xpReward: 360
    },
    {
        id: "72",
        worldId: 7,
        title: "The Pattern Finder",
        story: "Search for users whose names start with 'A'.",
        mission: "Use LIKE 'A%'.",
        rules: ["Partial match."],
        interviewInsight: "Pattern matching with % and _ allows for flexible search features.",
        initialCode: "const query = 'SELECT * FROM users WHERE name';\n",
        validationRegex: "LIKE\\s*(['\"])A%\\1",
        xpReward: 370
    },
    {
        id: "73",
        worldId: 7,
        title: "The Range Master",
        story: "Find values between 10 and 100.",
        mission: "Use the BETWEEN keyword.",
        rules: ["Range check."],
        interviewInsight: "BETWEEN is inclusive. It's often cleaner than >= and <= checks.",
        initialCode: "const query = 'SELECT * FROM stats WHERE level';\n",
        validationRegex: "BETWEEN\\s+10\\s+AND\\s+100",
        xpReward: 380
    },
    {
        id: "74",
        worldId: 7,
        title: "The IN Crowd",
        story: "We only want users from 'US', 'UK', and 'CA'.",
        mission: "Use the IN operator.",
        rules: ["Set membership."],
        interviewInsight: "IN is much more readable than multiple OR conditions.",
        initialCode: "const query = 'SELECT * FROM users WHERE country';\n",
        validationRegex: "IN\\s*\\(\\s*(['\"])US\\1\\s*,\\s*(['\"])UK\\2\\s*,\\s*(['\"])CA\\3\\s*\\)",
        xpReward: 390
    },
    {
        id: "75",
        worldId: 7,
        title: "The Count Sentinel",
        story: "How many souls dwell here?",
        mission: "Use COUNT(*) to find the total number of records.",
        rules: ["Count all."],
        interviewInsight: "Counting is the simplest aggregate but essential for analytics.",
        initialCode: "const query = 'SELECT FROM users';\n",
        validationRegex: "COUNT\\(\\s*\\*\\s*\\)",
        xpReward: 400
    },
    {
        id: "76",
        worldId: 7,
        title: "The Sum of Wealth",
        story: "Calculate the total gold in the treasury.",
        mission: "Use SUM(gold).",
        rules: ["Total sum."],
        interviewInsight: "SUM and AVG are the backbone of financial and statistical reporting.",
        initialCode: "const query = 'SELECT FROM treasury';\n",
        validationRegex: "SUM\\(\\s*gold\\s*\\)",
        xpReward: 410
    },
    {
        id: "77",
        worldId: 7,
        title: "The Min/Max Peak",
        story: "Find the strongest and weakest.",
        mission: "Use MIN(power) and MAX(power).",
        rules: ["Extrema detection."],
        interviewInsight: "MIN/MAX help identify outliers and ranges in your datasets.",
        initialCode: "const query = 'SELECT FROM stats';\n",
        validationRegex: "MIN.*MAX",
        xpReward: 420
    },
    {
        id: "78",
        worldId: 7,
        title: "The Grouping Torch",
        story: "Organize the population by country.",
        mission: "Use GROUP BY country.",
        rules: ["Aggregation grouping."],
        interviewInsight: "GROUP BY is where true data analysis begins. It collapses rows into segments.",
        initialCode: "const query = 'SELECT country, COUNT(*) FROM users';\n",
        validationRegex: "GROUP\\s+BY\\s+country",
        xpReward: 430
    },
    {
        id: "79",
        worldId: 7,
        title: "The Having Shield",
        story: "Only show countries with more than 100 users.",
        mission: "Use HAVING COUNT(*) > 100.",
        rules: ["Filter groups."],
        interviewInsight: "WHERE filters rows before grouping. HAVING filters groups after aggregation.",
        initialCode: "const query = 'SELECT country, COUNT(*) FROM users GROUP BY country';\n",
        validationRegex: "HAVING\\s+COUNT\\(\\s*\\*\\s*\\)\\s*>\\s*100",
        xpReward: 440
    },
    {
        id: "80",
        worldId: 7,
        title: "The Inner Join",
        story: "Join the User map with the Order records.",
        mission: "Use INNER JOIN orders ON users.id = orders.user_id.",
        rules: ["Combine tables."],
        interviewInsight: "Joins are the 'Relational' in RDBMS. Understanding them is 80% of SQL performance mastery.",
        initialCode: "const query = 'SELECT * FROM users';\n",
        validationRegex: "INNER\\s+JOIN\\s+orders\\s+ON",
        xpReward: 450
    },
    {
        id: "81",
        worldId: 7,
        title: "The Left Join",
        story: "Show all users, even those without orders.",
        mission: "Use LEFT JOIN orders.",
        rules: ["Preserve left table."],
        interviewInsight: "Left Joins are vital when you need a full list on one side despite missing related data.",
        initialCode: "const query = 'SELECT * FROM users';\n",
        validationRegex: "LEFT\\s+JOIN\\s+orders",
        xpReward: 460
    },
    {
        id: "82",
        worldId: 7,
        title: "The Subquery Secret",
        story: "A query within a query. Find users who earn more than average.",
        mission: "Use (SELECT AVG(salary) FROM users).",
        rules: ["Nested query."],
        interviewInsight: "Subqueries can simplify complex logic but watch out for performance; sometimes a Join is better.",
        initialCode: "const query = 'SELECT * FROM users WHERE salary >';\n",
        validationRegex: "\\(\\s*SELECT\\s+AVG",
        xpReward: 470
    },
    {
        id: "83",
        worldId: 7,
        title: "The Case Switch",
        story: "Label the scores: 'Low', 'High'.",
        mission: "Use CASE WHEN score > 50 THEN 'High' ELSE 'Low' END.",
        rules: ["Conditional logic."],
        interviewInsight: "CASE statements bring application-level conditional logic directly into your SQL results.",
        initialCode: "const query = 'SELECT name,';\n",
        validationRegex: "CASE\\s+WHEN.*THEN.*ELSE.*END",
        xpReward: 480
    },
    {
        id: "84",
        worldId: 7,
        title: "The Union Spark",
        story: "Combine two lists into one massive scroll.",
        mission: "Use UNION between two SELECT statements.",
        rules: ["Combine result sets."],
        interviewInsight: "UNION combines vertically. Fields must match in number and type across both queries.",
        initialCode: "const query = 'SELECT name FROM users';\n",
        validationRegex: "UNION\\s+SELECT",
        xpReward: 490
    },
    {
        id: "85",
        worldId: 7,
        title: "The Insert Rite",
        story: "A new soul enters the realm.",
        mission: "Use INSERT INTO users (name) VALUES ('Neo').",
        rules: ["Add data."],
        interviewInsight: "Insert puts data into persistence. Always specify columns to avoid brittle queries.",
        initialCode: "const query = '';\n",
        validationRegex: "INSERT\\s+INTO\\s+users.*VALUES",
        xpReward: 500
    },
    {
        id: "86",
        worldId: 7,
        title: "The Update Forge",
        story: "Level up a hero.",
        mission: "Use UPDATE users SET level = 10 WHERE name = 'Neo'.",
        rules: ["Modify data."],
        interviewInsight: "Always use a WHERE clause with UPDATE. Forgetting it will level up the entire database!",
        initialCode: "const query = '';\n",
        validationRegex: "UPDATE\\s+users\\s+SET\\s+level\\s*=\\s*10",
        xpReward: 510
    },
    {
        id: "87",
        worldId: 7,
        title: "The Delete Void",
        story: "Remove the shadow.",
        mission: "Use DELETE FROM users WHERE id = 99.",
        rules: ["Remove data."],
        interviewInsight: "Deletion is permanent. Use 'Soft Deletes' (status column) in mission-critical systems.",
        initialCode: "const query = '';\n",
        validationRegex: "DELETE\\s+FROM\\s+users",
        xpReward: 520
    },
    {
        id: "88",
        worldId: 7,
        title: "The Table Architect",
        story: "Build a new structure.",
        mission: "Use CREATE TABLE posts (id INT, title TEXT).",
        rules: ["Define schema."],
        interviewInsight: "DDL (Data Definition Language) defines the rules of your data world.",
        initialCode: "const query = '';\n",
        validationRegex: "CREATE\\s+TABLE\\s+posts",
        xpReward: 530
    },
    {
        id: "89",
        worldId: 7,
        title: "The Constraint Lock",
        story: "Ensure every record is unique.",
        mission: "Add PRIMARY KEY to the id column.",
        rules: ["Unique identification."],
        interviewInsight: "Primary keys are the identity of your data. No table should be without one.",
        initialCode: "const query = 'CREATE TABLE users (id INT';\n",
        validationRegex: "PRIMARY\\s+KEY",
        xpReward: 540
    },
    {
        id: "90",
        worldId: 7,
        title: "The Index Wind",
        story: "Speed up the search across the mountains.",
        mission: "Use CREATE INDEX name_idx ON users (name).",
        rules: ["Optimization."],
        interviewInsight: "Indexes make reading fast but writing slow. Use them strategically on frequently queried columns.",
        initialCode: "const query = '';\n",
        validationRegex: "CREATE\\s+INDEX",
        xpReward: 550
    },
    {
        id: "91",
        worldId: 7,
        title: "The Transaction Seal",
        story: "All or nothing.",
        mission: "Use BEGIN and COMMIT.",
        rules: ["Atomicity."],
        interviewInsight: "Transactions (ACID) ensure that complex operations succeed totally or fail cleanly.",
        initialCode: "const query = 'UPDATE...';\n",
        validationRegex: "BEGIN.*COMMIT",
        xpReward: 560
    },
    {
        id: "92",
        worldId: 7,
        title: "The Foreign Key",
        story: "Link the child to the parent.",
        mission: "Use REFERENCES users(id).",
        rules: ["Relational integrity."],
        interviewInsight: "Foreign keys prevent 'Orphan Records' and maintain the graph of your database.",
        initialCode: "const query = 'CREATE TABLE orders (user_id INT ';\n",
        validationRegex: "REFERENCES\\s+users\\(\\s*id\\s*\\)",
        xpReward: 570
    },
    {
        id: "93",
        worldId: 7,
        title: "The View Crystal",
        story: "Save a complex query for later.",
        mission: "Use CREATE VIEW active_users AS...",
        rules: ["Virtual tables."],
        interviewInsight: "Views simplify complex reports and can provide a security layer by hiding raw tables.",
        initialCode: "const query = '';\n",
        validationRegex: "CREATE\\s+VIEW",
        xpReward: 580
    },
    {
        id: "94",
        worldId: 7,
        title: "The CTE Ladder",
        story: "A temporary ladder for a tall building.",
        mission: "Use WITH temp_table AS (...).",
        rules: ["Common Table Expressions."],
        interviewInsight: "CTEs make complex SQL readable and maintainable compared to nested subqueries.",
        initialCode: "const query = '';\n",
        validationRegex: "WITH\\s+.*AS",
        xpReward: 590
    },
    {
        id: "95",
        worldId: 7,
        title: "The Normalization Scale",
        story: "Balance the data. Split 1NF into 2NF.",
        mission: "Assign '2NF' to `answer`.",
        rules: ["Database normalization."],
        interviewInsight: "Normalization reduces redundancy and improves data integrity (Third Normal Form is usually the goal).",
        initialCode: "const answer = '';\n",
        validationRegex: "2NF",
        xpReward: 600
    },
    {
        id: "96",
        worldId: 7,
        title: "Boss Fight: Data Architect",
        story: "The monolithic table is crumbling. Re-architect it.",
        mission: "1. Create Table. 2. Add FK. 3. Query with Join.",
        rules: ["Complex logic."],
        interviewInsight: "An architect sees schemas where others see lists. Design for the future.",
        initialCode: "function schema() {\n  // 1. Create\n  // 2. Link\n  // 3. Join\n}\n",
        validationRegex: "CREATE.*REFERENCES.*JOIN",
        xpReward: 1000
    },
    {
        id: "97",
        worldId: 14,
        title: "The Window Eye",
        story: "Look at the rows around you.",
        mission: "Use OVER (PARTITION BY category).",
        rules: ["Window functions."],
        interviewInsight: "Window functions allow aggregation without collapsing rows. Essential for complex reporting.",
        initialCode: "const query = 'SELECT name, AVG(score) ';\n",
        validationRegex: "OVER\\s*\\(\\s*PARTITION\\s+BY",
        xpReward: 610
    },
    {
        id: "98",
        worldId: 14,
        title: "The JSON Key",
        story: "Semi-structured data in a rigid world.",
        mission: "Use JSON_EXTRACT(data, '$.id').",
        rules: ["JSON querying."],
        interviewInsight: "Modern SQL databases handle JSON for flexibility while maintaining relational power.",
        initialCode: "const query = 'SELECT FROM logs';\n",
        validationRegex: "JSON_EXTRACT",
        xpReward: 620
    },
    {
        id: "99",
        worldId: 14,
        title: "The Full-Text Search",
        story: "Find the words in the mountain of scrolls.",
        mission: "Use MATCH (content) AGAINST ('magic').",
        rules: ["Indexing text."],
        interviewInsight: "Full-text indexes are optimized for searching large text bodies, far faster than LIKE '%word%'.",
        initialCode: "const query = 'SELECT * FROM posts WHERE';\n",
        validationRegex: "MATCH.*AGAINST",
        xpReward: 630
    },
    {
        id: "100",
        worldId: 14,
        title: "The Sharded Realm",
        story: "The data is too big for one world. Split it.",
        mission: "Assign 'Sharding' to `strategy`.",
        rules: ["Horizontal partitioning."],
        interviewInsight: "Sharding distributes data across multiple machines. It's the ultimate scale for massive datasets.",
        initialCode: "const strategy = '';\n",
        validationRegex: "Sharding",
        xpReward: 640
    },
    {
        id: "101",
        worldId: 8,
        title: "The Pull Request",
        story: "Submit for review.",
        mission: "Assign 'Pull Request' to `ans`.",
        rules: ["Peer review."],
        interviewInsight: "The PR is where collective intelligence improves your code.",
        initialCode: "const ans = '';\n",
        validationRegex: "Pull\\s+Request",
        xpReward: 200
    },
    {
        id: "102",
        worldId: 6,
        title: "The Docker Seal",
        story: "Run anywhere.",
        mission: "Assign 'Dockerfile' to `file`.",
        rules: ["Containerization."],
        interviewInsight: "Docker kills 'it worked on my machine' once and for all.",
        initialCode: "const file = '';\n",
        validationRegex: "Dockerfile",
        xpReward: 300
    },
    {
        id: "103",
        worldId: 8,
        title: "The Env Secret",
        story: "Hide in plain sight.",
        mission: "Assign `process.env.KEY` to `val`.",
        rules: ["Secret management."],
        interviewInsight: "Never commit keys. Use environment variables for config.",
        initialCode: "const val = '';\n",
        validationRegex: "process\\.env",
        xpReward: 310
    },
    {
        id: "104",
        worldId: 8,
        title: "The Vertical Scaling",
        story: "Build taller.",
        mission: "Assign 'Vertical' to `type`.",
        rules: ["Resources upgrade."],
        interviewInsight: "Scale up for power, scale out for reliability.",
        initialCode: "const type = '';\n",
        validationRegex: "Vertical",
        xpReward: 320
    },
    {
        id: "105",
        worldId: 8,
        title: "The Load Balancer",
        story: "Distribute the weight.",
        mission: "Assign 'Balancer' to `tool`.",
        rules: ["High availability."],
        interviewInsight: "A balancer is the traffic cop of high-traffic systems.",
        initialCode: "const tool = '';\n",
        validationRegex: "Balancer",
        xpReward: 330
    },
    {
        id: "106",
        worldId: 8,
        title: "Boss Fight: Deployment",
        story: "Final bridge.",
        mission: "Git and Env check.",
        rules: ["Commit and Secret."],
        interviewInsight: "Deployment is when your code finally meets the world.",
        initialCode: "function ship() {}\n",
        validationRegex: "commit.*env",
        xpReward: 600
    },
    {
        id: "107",
        worldId: 9,
        title: "The Microservice Cloud",
        story: "The Distributed Realm.",
        mission: "Assign 'API Gateway' to `entryPoint`.",
        rules: ["System entry point."],
        interviewInsight: "Microservices trade local complexity for network complexity.",
        initialCode: "const entryPoint = '';\n",
        validationRegex: "API Gateway",
        xpReward: 400
    },
    {
        id: "108",
        worldId: 9,
        title: "The Redis Cache",
        story: "Memory-fast retrieval.",
        mission: "Use `cache.set('key', 'val')`.",
        rules: ["Fast storage."],
        interviewInsight: "Caching is the best performance multiplier for expensive operations.",
        initialCode: "const cache = { set: () => {} };\n",
        validationRegex: "set\\(",
        xpReward: 410
    },
    {
        id: "109",
        worldId: 9,
        title: "The Event Dispatcher",
        story: "Pub/Sub communication.",
        mission: "Use `bus.publish('event')`.",
        rules: ["Asynchronous messaging."],
        interviewInsight: "Decouple services using an event-driven architecture.",
        initialCode: "const bus = { publish: () => {} };\n",
        validationRegex: "publish",
        xpReward: 420
    },
    {
        id: "110",
        worldId: 9,
        title: "The CI/CD Pipeline",
        story: "Auto-pilot for code.",
        mission: "Assign 'Pipeline' to `flow`.",
        rules: ["Delivery automation."],
        interviewInsight: "Continuous deployment is the maturity mark of a dev team.",
        initialCode: "const flow = '';\n",
        validationRegex: "Pipeline",
        xpReward: 430
    },
    {
        id: "111",
        worldId: 9,
        title: "The Blue-Green Bridge",
        story: "Zero-downtime transition.",
        mission: "Assign 'Blue-Green' to `strategy`.",
        rules: ["Deployment patterns."],
        interviewInsight: "Blue-green allows instant rollback if the new version fails.",
        initialCode: "const strategy = '';\n",
        validationRegex: "Blue-Green",
        xpReward: 440
    },
    {
        id: "112",
        worldId: 10,
        title: "The Single Responsibility",
        story: "The S of SOLID.",
        mission: "Assign 'One' to `responsibilities`.",
        rules: ["SOLID Principles."],
        interviewInsight: "A class should have one, and only one, reason to change.",
        initialCode: "const responsibilities = '';\n",
        validationRegex: "One",
        xpReward: 450
    },
    {
        id: "113",
        worldId: 10,
        title: "The Open-Closed Gate",
        story: "Open for extension.",
        mission: "Assign 'true' to `isClosed`.",
        rules: ["O of SOLID."],
        interviewInsight: "Extend behavior without modification.",
        initialCode: "const isClosed = false;\n",
        validationRegex: "true",
        xpReward: 460
    },
    {
        id: "114",
        worldId: 10,
        title: "The Liskov Swap",
        story: "Substitutable subclasses.",
        mission: "Assign 'L' to `letter`.",
        rules: ["L of SOLID."],
        interviewInsight: "Derived classes must be usable through the base class interface.",
        initialCode: "const letter = '';\n",
        validationRegex: "L",
        xpReward: 470
    },
    {
        id: "115",
        worldId: 10,
        title: "The Segregated Lens",
        story: "Specific interfaces.",
        mission: "Assign 'Interface' to `seg`.",
        rules: ["I of SOLID."],
        interviewInsight: "Keep interfaces small and focused.",
        initialCode: "const seg = '';\n",
        validationRegex: "Interface",
        xpReward: 480
    },
    {
        id: "116",
        worldId: 10,
        title: "The Dependency Inverse",
        story: "Depend on abstractions.",
        mission: "Assign 'D' to `letter`.",
        rules: ["D of SOLID."],
        interviewInsight: "DI makes code testable and flexible.",
        initialCode: "const letter = '';\n",
        validationRegex: "D",
        xpReward: 490
    },
    {
        id: "117",
        worldId: 11,
        title: "The Singleton Monolith",
        story: "Only one.",
        mission: "Assign 'instance' to `unique`.",
        rules: ["Patterns."],
        interviewInsight: "Singletons ensure a single global point of access.",
        initialCode: "const unique = '';\n",
        validationRegex: "instance",
        xpReward: 500
    },
    {
        id: "118",
        worldId: 11,
        title: "The Factory Floor",
        story: "Object creation.",
        mission: "Call `factory.create()`.",
        rules: ["De-coupling."],
        interviewInsight: "Factories shield callers from class instantiation logic.",
        initialCode: "const factory = { create: () => {} };\n",
        validationRegex: "create",
        xpReward: 510
    },
    {
        id: "119",
        worldId: 11,
        title: "The Observer Watcher",
        story: "Notify others.",
        mission: "Call `subject.notify()`.",
        rules: ["Reactive."],
        interviewInsight: "Observers power event-driven UI updates.",
        initialCode: "const subject = { notify: () => {} };\n",
        validationRegex: "notify",
        xpReward: 520
    },
    {
        id: "120",
        worldId: 11,
        title: "The Strategy Path",
        story: "Runtime logic choice.",
        mission: "Assign `new Slow()` to `strat`.",
        rules: ["Swappable."],
        interviewInsight: "Strategy pattern replaces complex switch statements.",
        initialCode: "let strat = null;\n",
        validationRegex: "Slow",
        xpReward: 530
    },
    {
        id: "121",
        worldId: 11,
        title: "The Decorator Bloom",
        story: "Layering extensions.",
        mission: "Assign `wrap(obj)` to `dec`.",
        rules: ["Dynamic."],
        interviewInsight: "Decorators add behavior without inheritance bloating.",
        initialCode: "const dec = '';\n",
        validationRegex: "wrap",
        xpReward: 540
    },
    {
        id: "122",
        worldId: 12,
        title: "Algorithm: Binary Search",
        story: "Dividing the world.",
        mission: "Assign 'O(log n)' to `eff`.",
        rules: ["Logarithmic."],
        interviewInsight: "B-Search is the core of efficient querying.",
        initialCode: "const eff = '';\n",
        validationRegex: "log",
        xpReward: 500
    },
    {
        id: "123",
        worldId: 12,
        title: "Algorithm: Merge Sort",
        story: "Divide and conquer.",
        mission: "Assign 'O(n log n)' to `eff`.",
        rules: ["Sorting."],
        interviewInsight: "N log N is optimal for comparison-based sorting.",
        initialCode: "const eff = '';\n",
        validationRegex: "n log n",
        xpReward: 510
    },
    {
        id: "124",
        worldId: 12,
        title: "The Linked List",
        story: "Chains of nodes.",
        mission: "Assign `node.next` to `link`.",
        rules: ["Structure."],
        interviewInsight: "Lists excel at constant-time insertions.",
        initialCode: "const link = '';\n",
        validationRegex: "next",
        xpReward: 520
    },
    {
        id: "125",
        worldId: 12,
        title: "The Tree Climber",
        story: "Hierarchical data.",
        mission: "Assign `root.left` to `br`.",
        rules: ["Trees."],
        interviewInsight: "Trees are essential for filesystem and DOM models.",
        initialCode: "const br = '';\n",
        validationRegex: "left",
        xpReward: 530
    },
    {
        id: "126",
        worldId: 12,
        title: "The Graph Map",
        story: "Everything connected.",
        mission: "Assign 'Network' to `mod`.",
        rules: ["Theory."],
        interviewInsight: "Graphs model the most complex real-world relationship datasets.",
        initialCode: "const mod = '';\n",
        validationRegex: "Network",
        xpReward: 540
    },
    {
        id: "127",
        worldId: 13,
        title: "The Resume Shield",
        story: "Arena entrance.",
        mission: "Assign 'Projects' to `sec`.",
        rules: ["Career."],
        interviewInsight: "Show impact through specific project outcomes.",
        initialCode: "const sec = '';\n",
        validationRegex: "Projects",
        xpReward: 600
    },
    {
        id: "128",
        worldId: 13,
        title: "The Behavioral Round",
        story: "Tell a story.",
        mission: "Assign 'STAR' to `m`.",
        rules: ["Methods."],
        interviewInsight: "STAR provides a compelling narrative for soft-skill questions.",
        initialCode: "const m = '';\n",
        validationRegex: "STAR",
        xpReward: 610
    },
    {
        id: "129",
        worldId: 13,
        title: "System Design Master",
        story: "Build the giants.",
        mission: "Assign 'Scale' to `goal`.",
        rules: ["Architecture."],
        interviewInsight: "Design for scale, availability, and maintainability.",
        initialCode: "const goal = '';\n",
        validationRegex: "Scale",
        xpReward: 620
    },
    {
        id: "130",
        worldId: 13,
        title: "The Coding Challenge",
        story: "Solve the puzzle.",
        mission: "Assign 'Clarity' to `p`.",
        rules: ["Logic."],
        interviewInsight: "Readable code is maintainable code.",
        initialCode: "const p = '';\n",
        validationRegex: "Clarity",
        xpReward: 630
    },
    {
        id: "131",
        worldId: 13,
        title: "The Salary Negotiation",
        story: "Final battle.",
        mission: "Assign 'Research' to `w`.",
        rules: ["Negotiate."],
        interviewInsight: "Information is your greatest asset in negotiation.",
        initialCode: "const w = '';\n",
        validationRegex: "Research",
        xpReward: 640
    },
    {
        id: "132",
        worldId: 14,
        title: "Boss Fight: Grand Senior",
        story: "Throne room.",
        mission: "Architect blueprint.",
        rules: ["Design, Scale, Test."],
        interviewInsight: "Full-lifecycle mastery is the key to senior leadership.",
        initialCode: "function architect() {}\n",
        validationRegex: "design.*scale.*test",
        xpReward: 1000
    },
    {
        id: "133",
        worldId: 14,
        title: "The Tech Lead",
        story: "Mentorship and vision.",
        mission: "Assign 'Mentorship' to `d`.",
        rules: ["Leadership."],
        interviewInsight: "Leading means raising the bar for the entire team.",
        initialCode: "const d = '';\n",
        validationRegex: "Mentorship",
        xpReward: 700
    },
    {
        id: "134",
        worldId: 14,
        title: "The Innovation Spark",
        story: "Stay curious.",
        mission: "Assign 'Curiosity' to `dr`.",
        rules: ["Learning."],
        interviewInsight: "Continuous learning prevents tech obsolescence.",
        initialCode: "const dr = '';\n",
        validationRegex: "Curiosity",
        xpReward: 710
    },
    {
        id: "135",
        worldId: 14,
        title: "The Developer Legacy",
        story: "What remains?",
        mission: "Assign 'Impact' to `res`.",
        rules: ["Purpose."],
        interviewInsight: "Your legacy is the quality and stability of your systems.",
        initialCode: "const res = '';\n",
        validationRegex: "Impact",
        xpReward: 720
    },
    {
        id: "136",
        worldId: 14,
        title: "Master of Dev",
        story: "Journey complete.",
        mission: "Assign 'Master' to `rank`.",
        rules: ["Total Mastery."],
        interviewInsight: "You have conquered the Dev World. Onwards!",
        initialCode: "const rank = '';\n",
        validationRegex: "Master",
        xpReward: 5000
    }
];

